<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>AnyProtocol.Protocol.RabbitMq</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="RabbitMQ.Client" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnyProtocol\AnyProtocol.csproj" />
    <ProjectReference Include="..\AnyProtocol.Abstraction\AnyProtocol.Abstraction.csproj" />
    <ProjectReference Include="..\AnyProtocol.Protocol.Abstraction\AnyProtocol.Protocol.Abstraction.csproj" />
  </ItemGroup>

</Project>
