<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>AnyProtocol.Protocol.Kafka</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Confluent.Kafka" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AnyProtocol\AnyProtocol.csproj" />
      <ProjectReference Include="..\AnyProtocol.Abstraction\AnyProtocol.Abstraction.csproj" />
      <ProjectReference Include="..\AnyProtocol.Protocol.Abstraction\AnyProtocol.Protocol.Abstraction.csproj" />
    </ItemGroup>

</Project>
