<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OrderSystem.Contracts\OrderSystem.Contracts.csproj" />
    <ProjectReference Include="..\..\..\src\AnyProtocol\AnyProtocol.csproj" />
    <ProjectReference Include="..\..\..\src\AnyProtocol.DependencyInjection.Microsoft\AnyProtocol.DependencyInjection.Microsoft.csproj" />
    <ProjectReference Include="..\..\..\src\AnyProtocol.Protocol.Rest.AspNetCore\AnyProtocol.Protocol.Rest.AspNetCore.csproj" />
    <ProjectReference Include="..\..\..\src\AnyProtocol.Protocol.Grpc.AspNetCore\AnyProtocol.Protocol.Grpc.AspNetCore.csproj" />
    <ProjectReference Include="..\..\..\src\AnyProtocol.Mcp.AspNetCore\AnyProtocol.Mcp.AspNetCore.csproj" />
    <ProjectReference Include="..\..\..\src\AnyProtocol.Serializer.TextJson\AnyProtocol.Serializer.TextJson.csproj" />
  </ItemGroup>

</Project>
