<Project ToolsVersion="12.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
	<AssemblyName Condition="'$(AssemblyName)' == ''">$([System.String]::Copy('$(MSBuildProjectName)').Replace('AnyProtocol','AnyProtocol'))</AssemblyName>
	<IsPublishable>false</IsPublishable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
	<PackageReference Include="coverlet.msbuild">
	<PrivateAssets>all</PrivateAssets>
	<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	</PackageReference>
  </ItemGroup>
</Project>
