<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Update="coverlet.msbuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AnyProtocol.Conformance\AnyProtocol.Conformance.csproj" />
    <ProjectReference Include="..\..\src\AnyProtocol\AnyProtocol.csproj" />
    <ProjectReference Include="..\..\src\AnyProtocol.Protocol.InMemory\AnyProtocol.Protocol.InMemory.csproj" />
  </ItemGroup>
</Project>
