<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Update="coverlet.msbuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\samples\OrderSystem.McpHost\OrderSystem.McpHost.csproj"
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\..\src\AnyProtocol.Mcp.AspNetCore\AnyProtocol.Mcp.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\AnyProtocol.Protocol.InMemory\AnyProtocol.Protocol.InMemory.csproj" />
    <ProjectReference Include="..\..\src\AnyProtocol.Protocol.Grpc\AnyProtocol.Protocol.Grpc.csproj" />
    <ProjectReference Include="..\..\src\AnyProtocol.Protocol.Grpc.AspNetCore\AnyProtocol.Protocol.Grpc.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\AnyProtocol.Protocol.Rest\AnyProtocol.Protocol.Rest.csproj" />
    <ProjectReference Include="..\..\src\AnyProtocol.Protocol.Rest.AspNetCore\AnyProtocol.Protocol.Rest.AspNetCore.csproj" />
    <ProjectReference Include="..\..\src\AnyProtocol.Serializer.TextJson\AnyProtocol.Serializer.TextJson.csproj" />
  </ItemGroup>

</Project>
